/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package tictactoe;

import org.junit.Assert;
import org.junit.Test;

/**
* Test something.
*/
public class AppTest {
    @Test
    public void appHasGreeting() {
        App classUnderTest = new App();
        Assert.assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
