/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package tictactoe;

import tictactoe.client.GameController;

import java.util.Scanner;

/**
* Main.
*/
public class App {

    public static void main(String[] args) {
        GameController gameController = new GameController();
        while (true) {
            gameController.update();
            gameController.draw();
        }
    }
}
